'use client';

import ReputationBadge from '@/components/ReputationBadge';
import { User, UserClassification } from '@/lib/types';

// Demo leaderboard data
const leaderboardUsers: (User & { rank: number })[] = [
    {
        rank: 1,
        id: 'user-001',
        username: 'alice',
        email: 'alice@university.edu',
        reputation: 240,
        classification: 'Contributor',
        total_uploads: 100,
        total_downloads: 10,
        average_rating: 5.0,
        created_at: '2024-01-01',
        last_active_at: '2024-01-20',
        peer_id: 'peer-001',
        status: 'online'
    },
    {
        rank: 2,
        id: 'user-002',
        username: 'bob',
        email: 'bob@university.edu',
        reputation: 115,
        classification: 'Contributor',
        total_uploads: 50,
        total_downloads: 30,
        average_rating: 4.5,
        created_at: '2024-01-02',
        last_active_at: '2024-01-20',
        peer_id: 'peer-002',
        status: 'online'
    },
    {
        rank: 3,
        id: 'user-003',
        username: 'charlie',
        email: 'charlie@university.edu',
        reputation: 95,
        classification: 'Contributor',
        total_uploads: 45,
        total_downloads: 25,
        average_rating: 4.5,
        created_at: '2024-01-03',
        last_active_at: '2024-01-19',
        peer_id: 'peer-003',
        status: 'offline'
    },
    {
        rank: 4,
        id: 'user-004',
        username: 'diana',
        email: 'diana@university.edu',
        reputation: 70,
        classification: 'Contributor',
        total_uploads: 35,
        total_downloads: 20,
        average_rating: 4.0,
        created_at: '2024-01-04',
        last_active_at: '2024-01-20',
        peer_id: 'peer-004',
        status: 'online'
    },
    {
        rank: 5,
        id: 'user-005',
        username: 'eve',
        email: 'eve@university.edu',
        reputation: 50,
        classification: 'Neutral',
        total_uploads: 20,
        total_downloads: 20,
        average_rating: 3.0,
        created_at: '2024-01-05',
        last_active_at: '2024-01-18',
        peer_id: 'peer-005',
        status: 'offline'
    },
    {
        rank: 6,
        id: 'user-006',
        username: 'frank',
        email: 'frank@university.edu',
        reputation: 35,
        classification: 'Neutral',
        total_uploads: 15,
        total_downloads: 15,
        average_rating: 3.5,
        created_at: '2024-01-06',
        last_active_at: '2024-01-17',
        peer_id: 'peer-006',
        status: 'offline'
    },
    {
        rank: 7,
        id: 'user-007',
        username: 'grace',
        email: 'grace@university.edu',
        reputation: 20,
        classification: 'Neutral',
        total_uploads: 10,
        total_downloads: 10,
        average_rating: 3.0,
        created_at: '2024-01-07',
        last_active_at: '2024-01-16',
        peer_id: 'peer-007',
        status: 'offline'
    },
    {
        rank: 8,
        id: 'user-008',
        username: 'henry',
        email: 'henry@university.edu',
        reputation: -20,
        classification: 'Leecher',
        total_uploads: 5,
        total_downloads: 50,
        average_rating: 2.0,
        created_at: '2024-01-08',
        last_active_at: '2024-01-15',
        peer_id: 'peer-008',
        status: 'offline'
    },
];

const getRankIcon = (rank: number) => {
    switch (rank) {
        case 1: return '🥇';
        case 2: return '🥈';
        case 3: return '🥉';
        default: return `#${rank}`;
    }
};

export default function LeaderboardPage() {
    return (
        <div className="max-w-5xl mx-auto">
            {/* Header */}
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-gray-900">🏆 Leaderboard</h1>
                <p className="text-gray-600 mt-2">
                    Top contributors in the P2P Academic Library network.
                </p>
            </div>

            {/* Go Concept Highlight */}
            <div className="card mb-6 bg-gradient-to-r from-rose-50 to-pink-50 border-rose-200">
                <div className="flex items-start gap-4">
                    <div className="concept-number shrink-0">4</div>
                    <div>
                        <h3 className="font-semibold text-gray-900">Go Concept: Maps & Structs</h3>
                        <p className="text-sm text-gray-600 mt-1">
                            Users are stored in a <code className="bg-white/50 px-1 rounded">map[UserID]*User</code>.
                            The leaderboard is generated by sorting the slice by reputation.
                        </p>
                        <pre className="mt-2 text-xs bg-white/70 p-2 rounded font-mono">
                            {`func GetLeaderboard(limit int) ([]*User, error) {
    users := make([]*User, 0, len(store))
    for _, user := range store {
        users = append(users, user)
    }
    sort.Slice(users, func(i, j int) bool {
        return users[i].Reputation > users[j].Reputation
    })
    return users[:limit], nil
}`}
                        </pre>
                    </div>
                </div>
            </div>

            {/* Top 3 Podium */}
            <div className="grid grid-cols-3 gap-4 mb-8">
                {/* Second Place */}
                <div className="card text-center pt-12 relative">
                    <div className="absolute top-4 left-1/2 -translate-x-1/2 text-4xl">🥈</div>
                    <div className="w-16 h-16 rounded-full bg-gradient-to-br from-gray-200 to-gray-300 mx-auto mb-3 flex items-center justify-center text-2xl font-bold text-gray-600">
                        {leaderboardUsers[1]?.username.charAt(0).toUpperCase()}
                    </div>
                    <h3 className="font-semibold text-gray-900">{leaderboardUsers[1]?.username}</h3>
                    <p className="text-2xl font-bold text-gray-600 mt-1">{leaderboardUsers[1]?.reputation}</p>
                    <ReputationBadge classification={leaderboardUsers[1]?.classification as UserClassification} score={leaderboardUsers[1]?.reputation} showScore={false} size="sm" />
                </div>

                {/* First Place */}
                <div className="card text-center pt-8 relative bg-gradient-to-b from-yellow-50 to-white border-yellow-300">
                    <div className="absolute top-2 left-1/2 -translate-x-1/2 text-5xl">🥇</div>
                    <div className="w-20 h-20 rounded-full bg-gradient-to-br from-yellow-300 to-yellow-500 mx-auto mb-3 flex items-center justify-center text-3xl font-bold text-white mt-4">
                        {leaderboardUsers[0]?.username.charAt(0).toUpperCase()}
                    </div>
                    <h3 className="font-bold text-lg text-gray-900">{leaderboardUsers[0]?.username}</h3>
                    <p className="text-3xl font-bold text-yellow-600 mt-1">{leaderboardUsers[0]?.reputation}</p>
                    <ReputationBadge classification={leaderboardUsers[0]?.classification as UserClassification} score={leaderboardUsers[0]?.reputation} showScore={false} size="md" />
                </div>

                {/* Third Place */}
                <div className="card text-center pt-12 relative">
                    <div className="absolute top-4 left-1/2 -translate-x-1/2 text-4xl">🥉</div>
                    <div className="w-16 h-16 rounded-full bg-gradient-to-br from-amber-200 to-amber-400 mx-auto mb-3 flex items-center justify-center text-2xl font-bold text-amber-800">
                        {leaderboardUsers[2]?.username.charAt(0).toUpperCase()}
                    </div>
                    <h3 className="font-semibold text-gray-900">{leaderboardUsers[2]?.username}</h3>
                    <p className="text-2xl font-bold text-amber-600 mt-1">{leaderboardUsers[2]?.reputation}</p>
                    <ReputationBadge classification={leaderboardUsers[2]?.classification as UserClassification} score={leaderboardUsers[2]?.reputation} showScore={false} size="sm" />
                </div>
            </div>

            {/* Full Leaderboard Table */}
            <div className="card">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">Full Rankings</h2>
                <div className="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th className="w-16">Rank</th>
                                <th>User</th>
                                <th>Classification</th>
                                <th className="text-center">Uploads</th>
                                <th className="text-center">Downloads</th>
                                <th className="text-center">Avg Rating</th>
                                <th className="text-right">Score</th>
                            </tr>
                        </thead>
                        <tbody>
                            {leaderboardUsers.map((user) => (
                                <tr key={user.id}>
                                    <td className="font-medium">
                                        <span className="text-xl">{getRankIcon(user.rank)}</span>
                                    </td>
                                    <td>
                                        <div className="flex items-center gap-3">
                                            <div className={`w-10 h-10 rounded-full flex items-center justify-center text-white font-bold ${user.status === 'online' ? 'bg-green-500' : 'bg-gray-400'
                                                }`}>
                                                {user.username.charAt(0).toUpperCase()}
                                            </div>
                                            <div>
                                                <p className="font-medium text-gray-900">{user.username}</p>
                                                <p className="text-sm text-gray-500">{user.status === 'online' ? '🟢 Online' : '⚫ Offline'}</p>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <ReputationBadge
                                            classification={user.classification as UserClassification}
                                            score={user.reputation}
                                            showScore={false}
                                            size="sm"
                                        />
                                    </td>
                                    <td className="text-center font-medium text-green-600">↑ {user.total_uploads}</td>
                                    <td className="text-center font-medium text-blue-600">↓ {user.total_downloads}</td>
                                    <td className="text-center">
                                        <span className="text-yellow-500">{'★'.repeat(Math.round(user.average_rating))}</span>
                                        <span className="text-gray-300">{'★'.repeat(5 - Math.round(user.average_rating))}</span>
                                    </td>
                                    <td className="text-right">
                                        <span className={`font-bold text-lg ${user.reputation > 50 ? 'text-green-600' :
                                                user.reputation >= 0 ? 'text-yellow-600' : 'text-red-600'
                                            }`}>
                                            {user.reputation}
                                        </span>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}
